version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/emendas_participativas
      - JWT_SECRET=sua-chave-secreta-aqui
      - NEXTAUTH_SECRET=sua-chave-secreta-aqui
      - NEXTAUTH_URL=http://localhost:3000
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=emendas_participativas
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 